### ISSUE TITLE
Maximum Upload size limits 

### ISSUE THREAD

**Issue by kafleg** [boogah/big-dummy#1]
I tried a lot of time to import via WordPress Import Tools but failed. I tried by increasing the size as well.

**Comment by iqbalbary** [comment]
@kafleg Its a lot of data ~1.6 GB so its better if you download the [wp-content/uploads/](https://goo.gl/9zikQQ) folder directly.

**Comment by kafleg** [comment]
@iqbalbary Thank you so much for the reply.
